### ISSUE TITLE
Subscribing to a hierarchy of topics

### ISSUE THREAD

**Issue by jaimejim** [core-wg/pubsub#11]
Given the following hierarchy:

"topic/subtopic1/subtopic2"

Should a subscriber be allowed to subscribe to topic or subtopic1? What would the broker return if so?

**Comment by mjkoster** [comment]
It depends on the content format requested by the subscriber. If there is only a link-format resource stored (sub topic but no data items) then the client can only get link-format.

**Comment by mjkoster** [comment]
The broker would return unsupported content format

**Comment by mjkoster** [comment]
4.15

**Comment by akeranen** [comment]
When subscribing to a parent topic, the broker will return a set of links that the client can subscribe to. The broker will send notifications when the link set changes so that a client stays up to date with the tree. This should work with the current draft already.
